// Students Information

const studentsInfo = [
  {
    name: "Iftiar Hossain",
    fathersName: "Gani Bepari",
    regNo: 5011,
    rollNo: 2011,
    passingYear: 2023,
    board: "Dhaka",
    gender: "Male",
    markPerSub: {
      ban: 40,
      eng: 45,
      math: 50,
      science: 55,
      socialScience: 60,
      religion: 70,
    },
  },
  {
    name: "Johurul Islam",
    fathersName: "Tara Mia",
    regNo: 5012,
    rollNo: 2012,
    passingYear: 2023,
    board: "Sylhet",
    gender: "Male",
    markPerSub: {
      ban: 33,
      eng: 60,
      math: 70,
      science: 45,
      socialScience: 60,
      religion: 80,
    },
  },
  {
    name: "Javed Aslam",
    fathersName: "Safin Aslam",
    regNo: 5013,
    rollNo: 2013,
    passingYear: 2022,
    board: "Comilla",
    gender: "Male",
    markPerSub: {
      ban: 40,
      eng: 45,
      math: 50,
      science: 55,
      socialScience: 60,
      religion: 70,
    },
  },
  {
    name: "Rina Akter",
    fathersName: "Nurjahan Begum",
    regNo: 5014,
    rollNo: 2014,
    passingYear: 2023,
    board: "Rajshahi",
    gender: "Female",
    markPerSub: {
      ban: 22,
      eng: 45,
      math: 50,
      science: 55,
      socialScience: 60,
      religion: 70,
    },
  },
];
